[package]
name = "micromanagermchghee"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"
windows = { "version"  = "0.58.0", "features" = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Dwm"] }

